import { DarkTheme, DefaultTheme, type Theme } from "@react-navigation/native";

export const THEME_METADATA = {
  light: {
    name: "Luz Clara",
    icon: "☀️",
    description: "Limpio y profesional",
    color: "#ffffff",
    item: "Cristal",
  },
  dark: {
    name: "Noche Oscura",
    icon: "🌙",
    description: "Elegante y minimalista",
    color: "#09090b",
    item: "Vacío",
  },
  onePiece: {
    name: "Gran Ruta",
    icon: "☠️",
    description: "¡Aventuras en el mar!",
    color: "#d91e1e",
    item: "Pergamino",
  },
  demonSlayer: {
    name: "Respiración Solar",
    icon: "⚔️",
    description: "Poder del sol y la espada",
    color: "#2d5f5d",
    item: "Katana",
  },
  naruto: {
    name: "Senda del Hokage",
    icon: "🍥",
    description: "Energía pura y determinación",
    color: "#ff9f1c",
    item: "Shuriken",
  },
  dragonBall: {
    name: "Guerrero Z",
    icon: "🐲",
    description: "Fuerza explosiva Saiyan",
    color: "#f28f08",
    item: "Esfera del Dragón",
  },
  strangerThings: {
    name: "Mundo del Revés",
    icon: "🧇",
    description: "Misterio ochentero láser",
    color: "#e20713",
    item: "Láser",
  },
};

export const DARK_THEMES = [
  "dark",
  "demonSlayer",
  "dragonBall",
  "strangerThings",
];

export const THEME = {
  light: {
    background: "#fdf5e6",
    foreground: "#2c1810",
    card: "#ffffff",
    cardForeground: "#2c1810",
    primary: "#d91e1e",
    primaryForeground: "#ffffff",
    border: "#e2e2e2",
    notification: "#ef4444",
    text: "#2c1810",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#d91e1e",
    info: "#2196f3",
  },
  dark: {
    background: "#09090b",
    foreground: "#fafafa",
    card: "#18181b",
    cardForeground: "#fafafa",
    primary: "#ff4444",
    primaryForeground: "#ffffff",
    border: "#27272a",
    notification: "#7f1d1d",
    text: "#fafafa",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#f44336",
    info: "#2196f3",
  },
  onePiece: {
    background: "#fdf5e6",
    foreground: "#2c1810",
    card: "#ffffff",
    cardForeground: "#2c1810",
    primary: "#d91e1e",
    primaryForeground: "#ffffff",
    border: "#2c1810",
    notification: "#ef4444",
    text: "#2c1810",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#d91e1e",
    info: "#2196f3",
  },
  demonSlayer: {
    background: "#121212",
    foreground: "#ffffff",
    card: "#1e1e1e",
    cardForeground: "#ffffff",
    primary: "#2d5f5d",
    primaryForeground: "#ffffff",
    border: "#2d5f5d",
    notification: "#ef4444",
    text: "#ffffff",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#f44336",
    info: "#2196f3",
  },
  naruto: {
    background: "#ffffff",
    foreground: "#2c2c2c",
    card: "#fff8e7",
    cardForeground: "#2c2c2c",
    primary: "#ff9f1c",
    primaryForeground: "#ffffff",
    border: "#ff9f1c",
    notification: "#ef4444",
    text: "#2c2c2c",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#f44336",
    info: "#2196f3",
  },
  dragonBall: {
    background: "#253294",
    foreground: "#ffffff",
    card: "#3a4db8",
    cardForeground: "#ffffff",
    primary: "#f28f08",
    primaryForeground: "#ffffff",
    border: "#f28f08",
    notification: "#ef4444",
    text: "#ffffff",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#f44336",
    info: "#2196f3",
  },
  strangerThings: {
    background: "#0b0b0b",
    foreground: "#ffffff",
    card: "#1a1a1a",
    cardForeground: "#ffffff",
    primary: "#e20713",
    primaryForeground: "#ffffff",
    border: "#e20713",
    notification: "#ef4444",
    text: "#ffffff",
    success: "#4caf50",
    warning: "#ff9800",
    error: "#e20713",
    info: "#2196f3",
  },
};

export const NAV_THEME: Record<string, Theme> = Object.entries(THEME).reduce(
  (acc, [key, val]) => {
    // Definimos qué temas son oscuros basándonos en su fondo
    const isDark = DARK_THEMES.includes(key);

    const baseTheme = isDark ? DarkTheme : DefaultTheme;
    acc[key] = {
      ...baseTheme,
      colors: {
        ...baseTheme.colors,
        background: val.background,
        border: val.border,
        card: val.card,
        notification: val.notification,
        primary: val.primary,
        text: val.text,
      },
    };
    return acc;
  },
  {} as Record<string, Theme>,
);
